# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TroyFarrell.com
author: Troy Farrell 2022
description: >- # this means to ignore newlines until "baseurl:"
  Troy Farrell: Software Architect and Developer.  Fan of improv, swimming, 
  cats and vacations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://troyfarrell.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: troyfarrell
github_username:  t2farrell
linkedin_username: troyfarrell
google_analytics: UA-3882901-1

# Build settings
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap

webrick:
  headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Content-Security-Policy: base-uri 'self'; default-src 'self' https://*.youtube.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; script-src 'self' https://code.jquery.com https://www.googletagmanager.com  https://www.google-analytics.com 'sha256-txg5QqYdtNrX4Ty0HRiXNlF4HZmmgwLWMmNJDNa0g48=' 'sha256-8/3DAdXYATNkOWw7dw/hdy9iis+Hzy7HmkzlavBsQyM=' 'sha256-ReAZKgSKiEvRqUgVZuk2knHDFkUu7EjHFJzW0WMlgkg='; img-src 'self' https://www.googletagmanager.com  https://www.google-analytics.com
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer-when-downgrade
    Permissions-Policy: camera=(), microphone=(), payment=(), usb=()

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - lib/
  - minima-ref/  #ignore reference copy of original minima theme
  - _img_work/
  - README.md
